#!/usr/bin/env python3
"""Update workspace tracker — sub-spec status updates.

Usage:
  .spec-workflow/sdd workspace/update-tracker.py
    --workspace <path> --target <feature>/<repo-id>
    --status <status> [--phase <phase>] [--auto-generated]
"""
import _bootstrap  # noqa: F401

from sdd_core import cli, handoffs, output, workspace

KNOWN_STATUSES = workspace.VALID_STATUSES

# Mirrors workflow-graph.json `sdd-workspace-create-spec.context_needs`.
__sdd_context_needs__ = ("target", "workspace", "repo_id", "phase")


def main() -> None:
    parser = cli.workspace_parser(
        "Update a sub-spec status in the workspace tracker",
    )
    parser.add_argument("--status", help="New sub-spec status")
    parser.add_argument("--phase", help="Current spec phase")
    parser.add_argument(
        "--doc-status",
        help="Directly set docStatus for a phase (e.g. 'reviewed'). "
             "Requires --phase to identify which document.",
    )
    parser.add_argument(
        "--review-skipped", action="store_true",
        help="Record that the user chose to skip review (audit trail). "
             "Used with --doc-status reviewed.",
    )
    parser.add_argument(
        "--auto-generated", action="store_true",
        help="Mark sub-spec as auto-generated from delegation context",
    )
    parser.add_argument(
        "--dry-run", action="store_true",
        help="Preview changes without writing to disk",
    )

    args = parser.parse_args()
    ctx = cli.resolve_context(
        args, needs=("target", "workspace", "repo_id", "phase"),
    )

    # ``repo_id`` is carried by the ``--target FEATURE/REPO-ID`` slash form.
    if not args.repo_id:
        output.error(
            "--target must include the repo id (`<feature>/<repo-id>`)",
            hint="e.g. --target my-feature/api-svc",
        )

    if not args.status and not args.doc_status:
        output.error(
            "At least one of --status or --doc-status is required.",
            hint="Use --status for sub-spec status, --doc-status for docStatus updates.",
        )

    if args.status and args.status not in KNOWN_STATUSES:
        output.error(
            f"Unknown status '{args.status}'",
            hint=f"Valid statuses: {sorted(KNOWN_STATUSES)}",
        )

    if args.doc_status and not args.phase:
        output.error(
            "--doc-status requires --phase to identify which document.",
            hint="e.g. --phase requirements --doc-status reviewed",
        )

    root = cli.resolve_workspace_root(args)
    tracker = workspace.read_tracker(root, args.feature)
    if not tracker:
        tracker = workspace.create_default_tracker(args.feature)

    if args.status:
        status_update: dict = {"status": args.status}
        if args.phase:
            status_update["phase"] = args.phase
        if args.auto_generated:
            status_update["autoGenerated"] = True

        try:
            tracker = workspace.update_sub_spec_status(tracker, args.repo_id, status_update)
        except ValueError as exc:
            output.error(
                str(exc),
                hint="Valid transitions from current status: see VALID_TRANSITIONS in workspace.py",
            )

    tracker_advisories: list[dict] = []
    if args.status and args.phase and args.phase in workspace.DOC_PHASES and not args.doc_status:
        try:
            workspace.update_doc_status(
                tracker, args.repo_id, args.phase, "created",
            )
        except ValueError as exc:
            tracker_advisories.append({
                "name": "doc-status-update-failed", "level": "warn",
                "message": f"Could not update docStatus: {exc}",
            })

    if args.doc_status and args.phase:
        try:
            workspace.update_doc_status(
                tracker, args.repo_id, args.phase, args.doc_status,
            )
        except ValueError as exc:
            output.error(
                f"Could not set docStatus.{args.phase} to '{args.doc_status}': {exc}",
                hint="Check DOC_STATUS_TRANSITIONS in workspace_phase.py for valid transitions.",
            )

        if args.review_skipped:
            from sdd_core import time as sdd_time
            sub = next(
                (s for s in tracker.get("subSpecs", []) if s.get("repoId") == args.repo_id),
                None,
            )
            if sub is not None:
                review_meta = sub.setdefault("reviewMeta", {})
                phase_meta = review_meta.setdefault(args.phase, {})
                phase_meta["reviewSkipped"] = True
                phase_meta["reviewSkippedAt"] = sdd_time.ts_now()

    description_parts = []
    if args.status:
        description_parts.append(f"status → {args.status}")
    if args.doc_status:
        description_parts.append(f"docStatus.{args.phase} → {args.doc_status}")
        if args.review_skipped:
            description_parts.append("reviewSkipped=true")
    description = ", ".join(description_parts)

    if args.dry_run:
        tracker["summary"] = workspace.calculate_summary(tracker)
        dry_data: dict = {"dryRun": True, "tracker": tracker}
        if tracker_advisories:
            dry_data["advisories"] = tracker_advisories
        output.success(
            dry_data,
            f"[dry-run] Would update {args.repo_id}: {description}",
            ctx=ctx,
            resolved_from=dict(ctx.resolved_from),
        )
        return

    workspace.finalize_and_save(root, args.feature, tracker)
    tracker_result: dict = {"tracker": tracker}
    if tracker_advisories:
        tracker_result["advisories"] = tracker_advisories
    output.success(
        tracker_result,
        f"Tracker updated: {args.repo_id} — {description}",
        ctx=ctx,
        resolved_from=dict(ctx.resolved_from),
        handoffs=handoffs.handoffs_for(handoffs.current_script_id(), ctx),
    )


if __name__ == "__main__":
    cli.run_main(main)
