"""Workspace batch approval: collect, summarize, and apply approvals."""
from __future__ import annotations

from pathlib import Path
from typing import Callable, TypedDict

from . import output as _output
from ._workspace_io import pending_batch_path
from .workspace_artifacts import RepoApprovalResult
from .workspace_manifest import ManifestData
from .workspace_tracker import (
    DOC_NAMES,
    TrackerData,
    TrackerSubSpec,
    calculate_summary,
    finalize_and_save,
    read_tracker,
    update_doc_approval,
    update_sub_spec_status,
)

__all__ = [
    "BatchApprovalResult",
    "PhaseApprovalResult",
    "collect_pending_subspecs",
    "require_pending_subspecs",
    "generate_approval_summary",
    "apply_batch_approval",
    "collect_phase_pending",
    "generate_phase_approval_summary",
    "apply_phase_approval",
    "create_pending_batch",
    "read_pending_batch",
    "cleanup_pending_batch",
]


class PhaseApprovalResult(TypedDict):
    """Aggregated outcome of a phase-approve batch.

    Atomic semantics: ``approved`` / ``preflight_required`` / ``failed``
    are mutually exclusive per repo. Tracker mutations only land when
    every repo is in ``approved``.
    """

    approved: list[RepoApprovalResult]
    preflight_required: list[RepoApprovalResult]
    failed: list[RepoApprovalResult]


class BatchApprovalResult(TypedDict):
    approved: list[str]
    failed: list[dict[str, str]]


def require_pending_subspecs(
    tracker: TrackerData,
    feature: str = "",
    status_filter: str | set[str] = "spec_created",
) -> list[TrackerSubSpec]:
    """Return pending sub-specs or an empty list if none match.

    ``feature`` is accepted for call-site readability (the workspace
    feature name) but is not used by the filter. The caller is
    responsible for deciding how to handle the empty case
    (e.g. exit gracefully, warn, or continue).
    """
    del feature  # accepted for readability; selection is status-based.
    return collect_pending_subspecs(tracker, status_filter)


def collect_pending_subspecs(
    tracker: TrackerData,
    status_filter: str | set[str] = "spec_created",
) -> list[TrackerSubSpec]:
    """Return sub-spec entries whose status matches *status_filter*.

    *status_filter* may be a single status string or a set of statuses.
    """
    if isinstance(status_filter, str):
        status_filter = {status_filter}
    return [
        s for s in tracker.get("subSpecs", [])
        if s.get("status") in status_filter
    ]


def _format_summary(
    manifest: ManifestData,
    tracker: TrackerData,
    pending: list[TrackerSubSpec],
    *,
    title: str,
    count_label: str,
    detail_fn: Callable[[TrackerSubSpec, dict], list[str]],
    footer_fn: Callable[[TrackerData, list[TrackerSubSpec]], list[str]] | None = None,
) -> str:
    """Shared summary formatter used by batch and phase approval summaries."""
    feature = manifest.get("feature", tracker.get("feature", "unknown"))
    repos_by_id: dict[str, dict] = {
        r["id"]: r for r in manifest.get("repos", [])
    }

    lines: list[str] = [
        f"{title} — {feature}",
        f"{'=' * 50}",
        f"{count_label}: {len(pending)}",
        "",
    ]

    for i, sub in enumerate(pending, 1):
        repo_id = sub.get("repoId", "unknown")
        repo_info = repos_by_id.get(repo_id, {})
        repo_name = repo_info.get("name", sub.get("repoName", repo_id))
        role = repo_info.get("role", "N/A")
        lines.append(f"  {i}. {repo_name} ({repo_id})")
        lines.extend(detail_fn(sub, repo_info))
        lines.append(f"     Role: {role}")
        lines.append("")

    if footer_fn is not None:
        lines.extend(footer_fn(tracker, pending))

    return "\n".join(lines)


def generate_approval_summary(
    manifest: ManifestData,
    tracker: TrackerData,
    pending: list[TrackerSubSpec],
) -> str:
    """Build a human-readable summary of sub-specs pending batch approval.

    Returns a formatted multi-line string listing each pending sub-spec
    with its repo name, role, and current status.
    """
    def _detail(sub: TrackerSubSpec, repo_info: dict) -> list[str]:
        sub_spec = repo_info.get("subSpec", sub.get("subSpecName", "N/A"))
        auto_tag = " [from delegation context]" if sub.get("autoGenerated") else ""
        return [
            f"     Sub-spec: {sub_spec}{auto_tag}",
            f"     Status: {sub.get('status', 'unknown')}",
        ]

    def _footer(trk: TrackerData, pend: list[TrackerSubSpec]) -> list[str]:
        summary = trk.get("summary", calculate_summary(trk))
        total = summary.get("totalSubSpecs", 0)
        already_approved = sum(
            1 for s in trk.get("subSpecs", [])
            if s.get("status") in ("approved", "in_progress", "completed")
        )
        return [
            f"Already approved: {already_approved}/{total}",
            f"Will approve:     {len(pend)}/{total}",
        ]

    return _format_summary(
        manifest, tracker, pending,
        title="Batch Approval Summary",
        count_label="Sub-specs pending approval",
        detail_fn=_detail,
        footer_fn=_footer,
    )


def _apply_approvals(tracker: TrackerData, subspecs: list[TrackerSubSpec]) -> tuple[TrackerData, BatchApprovalResult]:
    """Pure transformation: approve sub-specs in *tracker*, return (tracker, result).

    Does not perform I/O. The caller is responsible for persisting changes.
    """
    result: BatchApprovalResult = {"approved": [], "failed": []}

    for sub in subspecs:
        repo_id = sub.get("repoId", "")
        if not repo_id:
            result["failed"].append({"repoId": "(unknown)", "error": "Missing repoId"})
            continue

        try:
            tracker = update_sub_spec_status(
                tracker, repo_id,
                {"status": "approved"},
            )
            result["approved"].append(repo_id)
        except ValueError as exc:
            result["failed"].append({"repoId": repo_id, "error": str(exc)})

    return tracker, result


def _apply_doc_approvals(
    tracker: TrackerData,
    result: BatchApprovalResult,
    approval_id_map: dict[str, dict[str, str]] | None,
    timestamp: str,
) -> None:
    """Record per-document approval state for all successfully approved sub-specs."""
    for repo_id in result["approved"]:
        if approval_id_map and repo_id in approval_id_map:
            for doc, aid in approval_id_map[repo_id].items():
                update_doc_approval(tracker, repo_id, doc, aid, "approved", timestamp)
        else:
            for doc in DOC_NAMES:
                update_doc_approval(tracker, repo_id, doc, None, "approved", timestamp)


def apply_batch_approval(
    root: Path,
    feature: str,
    subspecs: list[TrackerSubSpec],
    *,
    tracker: TrackerData | None = None,
    approval_id_map: dict[str, dict[str, str]] | None = None,
) -> BatchApprovalResult:
    """Approve multiple sub-specs in a single pass.

    For each sub-spec in *subspecs*, transitions status from ``spec_created``
    to ``approved`` and records per-document approval state.

    *approval_id_map* is an optional mapping of
    ``{repo_id: {doc: approval_id}}``. When provided, records actual
    approval IDs from the formal approval flow. When ``None`` (batch
    shortcut), marks all three docs as approved without individual IDs.

    If *tracker* is provided it is used directly; otherwise it is read from
    disk.  The updated tracker is always persisted after the batch.

    Returns a :class:`BatchApprovalResult` with per-repo outcomes.
    Failures on individual sub-specs do not abort the batch — the remaining
    sub-specs are still processed.
    """
    from sdd_core import time as sdd_time

    if tracker is None:
        tracker = read_tracker(root, feature)
    if not tracker:
        raise FileNotFoundError(f"No tracker found for feature '{feature}'")

    tracker, result = _apply_approvals(tracker, subspecs)
    _apply_doc_approvals(tracker, result, approval_id_map, sdd_time.ts_now())
    finalize_and_save(root, feature, tracker)

    return result


def collect_phase_pending(
    tracker: TrackerData, doc: str,
) -> list[TrackerSubSpec]:
    """Active sub-specs with ``docStatus.{doc} == 'reviewed'`` (ready for approval).

    Excludes cancelled/failed repos so they are not erroneously approved.
    Requires the ``reviewed`` status (set after batch review or review-skip).
    """
    from . import workspace_query
    reviewed = workspace_query.filter_by_doc_status(tracker, doc, "reviewed")
    active_ids = {s.get("repoId") for s in workspace_query.active_repos(tracker)}
    return [s for s in reviewed if s.get("repoId") in active_ids]


def generate_phase_approval_summary(
    manifest: ManifestData,
    tracker: TrackerData,
    pending: list[TrackerSubSpec],
    doc: str,
) -> str:
    """Build a summary for phase-scoped approval (single doc type)."""
    def _detail(sub: TrackerSubSpec, _repo_info: dict) -> list[str]:
        doc_status = sub.get("docStatus", {}).get(doc, "unknown")
        return [f"     {doc}.md — status: {doc_status}"]

    return _format_summary(
        manifest, tracker, pending,
        title=f"Phase Approval Summary — {doc}",
        count_label=f"Repos ready for {doc} approval",
        detail_fn=_detail,
    )


def _create_repo_approval_artifacts(
    sub: TrackerSubSpec, doc: str, approval_id: str, timestamp: str,
) -> "RepoApprovalResult | None":
    """Delegate to ``workspace_artifacts.create_repo_approval_artifacts``.

    Indirection retained as a test-mock seam — patching this name lets
    the phase-approval tests stub the per-repo write without touching
    real disk state.
    """
    from .workspace_artifacts import create_repo_approval_artifacts
    return create_repo_approval_artifacts(sub, doc, approval_id, timestamp)


_PHASE_STATUS_MAP: dict[str, str] = {
    "requirements": "requirements_approved",
    "design": "design_approved",
    "tasks": "approved",
}


def apply_phase_approval(
    root: Path,
    feature: str,
    doc: str,
    subspecs: list[TrackerSubSpec],
    *,
    tracker: TrackerData | None = None,
    approval_id_map: dict[str, str] | None = None,
) -> PhaseApprovalResult:
    """Approve one doc type across repos atomically.

    Two-phase commit:

    1. **Aggregate.** Each repo's per-doc artifact write produces a
       :class:`RepoApprovalResult` (``approved`` / ``preflight_required``
       / ``failed``). The H1-actor refusal lands in ``preflight_required``.
    2. **Commit or abort.** Tracker doc-status / sub-spec-status mutations
       run **only** when every result is ``approved``. Any
       ``preflight_required`` aborts the batch — no partial advance.

    Returns a :class:`PhaseApprovalResult` with the per-bucket lists.
    """
    from sdd_core import time as sdd_time
    from .workspace_artifacts import create_repo_approval_artifacts
    from . import approvals

    if tracker is None:
        tracker = read_tracker(root, feature)
    if not tracker:
        raise FileNotFoundError(f"No tracker found for feature '{feature}'")

    timestamp = sdd_time.ts_now()
    repo_results: list[RepoApprovalResult] = []

    for sub in subspecs:
        repo_id = sub.get("repoId", "")
        if not repo_id:
            repo_results.append(RepoApprovalResult(
                repoId="(unknown)", outcome="failed",
                gate="missing-repo-id", reason="Missing repoId",
            ))
            continue
        aid = (approval_id_map or {}).get(repo_id) or approvals.create_approval_id()
        artifact_result = _create_repo_approval_artifacts(sub, doc, aid, timestamp)
        if not isinstance(artifact_result, dict):
            artifact_result = RepoApprovalResult(
                repoId=repo_id, outcome="approved",
            )
        artifact_result.setdefault("approvalId", aid)
        artifact_result.setdefault("repoId", repo_id)
        repo_results.append(artifact_result)

    approved = [r for r in repo_results if r.get("outcome") == "approved"]
    preflight = [r for r in repo_results if r.get("outcome") == "preflight_required"]
    failed = [r for r in repo_results if r.get("outcome") == "failed"]

    if preflight or failed:
        # Atomic: do not advance tracker. Caller surfaces the
        # preflight_required envelope; tracker stays at "reviewed".
        return PhaseApprovalResult(
            approved=approved, preflight_required=preflight, failed=failed,
        )

    # All approved — commit tracker mutations now.
    from . import workspace_phase

    for r in approved:
        repo_id = r["repoId"]
        aid = r.get("approvalId", "")
        try:
            workspace_phase.update_doc_status(tracker, repo_id, doc, "approved")
            update_doc_approval(tracker, repo_id, doc, aid, "approved", timestamp)
            target_status = _PHASE_STATUS_MAP.get(doc)
            if target_status:
                try:
                    update_sub_spec_status(tracker, repo_id, {"status": target_status})
                except ValueError as ve:
                    _output.warn(f"Status transition to '{target_status}' skipped for {repo_id}: {ve}")
        except ValueError as exc:
            # Tracker-only failure after artifacts succeeded — surface
            # as failed but keep the artifact in place for forensics.
            r["outcome"] = "failed"
            r["gate"] = "tracker-update"
            r["reason"] = str(exc)

    # Advance the phase tracker atomically before finalize_and_save so a
    # crash mid-write cannot leave currentPhase stale relative to the
    # per-repo docStatus mutations above.
    workspace_phase.advance_with_gate(tracker, doc)

    finalize_and_save(root, feature, tracker)

    # Re-bucket after tracker-update failures.
    approved = [r for r in repo_results if r.get("outcome") == "approved"]
    failed = [r for r in repo_results if r.get("outcome") == "failed"]
    return PhaseApprovalResult(
        approved=approved, preflight_required=preflight, failed=failed,
    )


def create_pending_batch(
    root: Path, feature: str, batch_type: str, repo_ids: list[str],
) -> Path:
    """Write a pending batch file listing repo IDs.  Returns the path."""
    path = pending_batch_path(root, feature, batch_type)
    data = {"feature": feature, "batchType": batch_type, "pendingRepoIds": repo_ids}
    _output.atomic_write_json(str(path), data)
    return path


def read_pending_batch(
    root: Path, feature: str, batch_type: str,
) -> list[str]:
    """Read repo IDs from the batch file.  Raises if missing."""
    path = pending_batch_path(root, feature, batch_type)
    if not path.is_file():
        raise FileNotFoundError(
            f"No pending batch file found at {path}. "
            f"Run the batch presentation step first."
        )
    data = _output.safe_read_json(path, default={})
    return data.get("pendingRepoIds", [])


def cleanup_pending_batch(
    root: Path, feature: str, batch_type: str,
) -> None:
    """Remove the batch file after confirmation."""
    path = pending_batch_path(root, feature, batch_type)
    if path.is_file():
        try:
            path.unlink()
        except OSError:
            pass
