"""Workspace tracker CRUD, status transitions, and summary calculation.

Facade module — re-exports from focused sub-modules:
- workspace_tracker_validation: schema and field validation
- workspace_tracker_domain: transitions, summary, polling, factory
"""
from __future__ import annotations

import warnings as _warnings
from dataclasses import dataclass
from pathlib import Path
from typing import Literal, TypedDict

from ._coerce import coerce_path
from .specs import DOC_NAMES
from . import time as sdd_time
from ._workspace_io import (
    read_workspace_file,
    require_workspace_file,
    write_workspace_file,
)
from .workspace_tracker_validation import (
    TRACKER_SCHEMA_VERSION,
    VALID_APPROVAL_STATUSES,
    VALID_STATUSES,
    validate_tracker_schema as _validate_tracker_schema,
)
from .workspace_repo_set import normalise_repo_set
from .workspace_tracker_domain import (
    VALID_TRANSITIONS,
    VALID_APPROVAL_TRANSITIONS,
    normalize_status,
    _status_to_summary_key,
    update_sub_spec_status,
    update_doc_approval,
    calculate_summary,
    derive_workspace_status,
    create_default_tracker,
    poll_sub_spec_status,
)

__all__ = [
    "VALID_TRANSITIONS",
    "VALID_APPROVAL_TRANSITIONS",
    "VALID_APPROVAL_STATUSES",
    "VALID_STATUSES",
    "TRACKER_SCHEMA_VERSION",
    "DOC_NAMES",
    "SubSpecStatus",
    "ApprovalDocStatus",
    "WorkspaceStatus",
    "DocApprovalRecord",
    "DocApprovals",
    "DocStatusMap",
    "TrackerSubSpec",
    "TrackerSummary",
    "PhaseStatusCounts",
    "ByPhaseSummary",
    "PhaseGateRecord",
    "PhaseGates",
    "WorkflowConfig",
    "TrackerData",
    "SubSpecUpdate",
    "PollResult",
    "TrackerReadResult",
    "read_tracker",
    "read_tracker_quiet",
    "write_tracker",
    "require_tracker",
    "create_default_tracker",
    "is_v2",
    "update_sub_spec_status",
    "update_doc_approval",
    "calculate_summary",
    "derive_workspace_status",
    "finalize_and_save",
    "poll_sub_spec_status",
    "write_initial_tracker",
    "tracker_repos_match",
    "mark_review_retroactive",
    "TrackerUpdateOutcome",
    "update_tracker_or_advisory",
    "iter_workspace_repo_roots",
]


SubSpecStatus = Literal[
    "pending", "spec_created", "rejected", "approved",
    "requirements_created", "requirements_approved",
    "design_created", "design_approved", "tasks_created",
    "in_progress", "blocked", "failed", "completed", "cancelled",
]

ApprovalDocStatus = Literal[
    "not_requested", "pending", "approved", "revision_requested", "rejected"
]

WorkspaceStatus = Literal["in_progress", "completed", "blocked", "cancelled"]


class _DocApprovalRecordRequired(TypedDict):
    status: ApprovalDocStatus


class DocApprovalRecord(_DocApprovalRecordRequired, total=False):
    approvalId: str | None
    timestamp: str | None


class DocApprovals(TypedDict, total=False):
    requirements: DocApprovalRecord
    design: DocApprovalRecord
    tasks: DocApprovalRecord


class DocStatusMap(TypedDict, total=False):
    requirements: str
    design: str
    tasks: str


class TrackerSubSpec(TypedDict, total=False):
    repoId: str
    repoName: str
    repoPath: str
    subSpecName: str
    repoType: str
    status: SubSpecStatus
    phase: str
    docStatus: DocStatusMap
    approvals: DocApprovals
    lastChecked: str
    autoGenerated: bool


class SubSpecUpdate(TypedDict, total=False):
    status: SubSpecStatus
    phase: str
    autoGenerated: bool


class PhaseStatusCounts(TypedDict, total=False):
    pending: int
    created: int
    validated: int
    reviewed: int
    approved: int
    skipped: int
    failed: int
    revision_requested: int


class ByPhaseSummary(TypedDict, total=False):
    requirements: PhaseStatusCounts
    design: PhaseStatusCounts
    tasks: PhaseStatusCounts


class TrackerSummary(TypedDict, total=False):
    totalSubSpecs: int
    completed: int
    inProgress: int
    pending: int
    blocked: int
    failed: int
    cancelled: int
    specCreated: int
    approved: int
    rejected: int
    requirementsCreated: int
    requirementsApproved: int
    designCreated: int
    designApproved: int
    tasksCreated: int
    approvedSubSpecs: int
    byPhase: ByPhaseSummary


class PhaseGateRecord(TypedDict, total=False):
    reviewedAt: str
    approvedAt: str
    reposApproved: list[str]
    reposSkipped: list[str]
    reposFailed: list[str]


class PhaseGates(TypedDict, total=False):
    requirements: PhaseGateRecord | None
    design: PhaseGateRecord | None
    tasks: PhaseGateRecord | None


class WorkflowConfig(TypedDict, total=False):
    mode: str
    phaseOrder: list[str]


class TrackerData(TypedDict, total=False):
    schemaVersion: str
    feature: str
    status: WorkspaceStatus
    currentPhase: str
    createdAt: str
    updatedAt: str
    coordinationApprovals: DocApprovals
    phaseGates: PhaseGates
    subSpecs: list[TrackerSubSpec]
    summary: TrackerSummary


class PollResult(TypedDict, total=False):
    repoId: str
    pollStatus: str
    phase: str
    status: str
    taskProgress: dict
    message: str


def read_tracker(root: "Path | str", feature: str) -> TrackerData:
    """Read workspace-tracker.json from workspace dir."""
    root = coerce_path(root)
    data = read_workspace_file(root, feature, "tracker")
    return _validate_tracker_schema(data)


@dataclass(frozen=True)
class TrackerReadResult:
    """Outcome of :func:`read_tracker_quiet` — data + captured advisories."""

    data: "TrackerData"
    advisories: tuple[str, ...]


def read_tracker_quiet(
    root: "Path | str", feature: str,
) -> TrackerReadResult:
    """Read tracker without leaking schema warnings to stderr.

    Enumeration callers (ledger walkers, cross-feature status probes)
    need to traverse every tracker on disk. The standard
    :func:`read_tracker` routes legacy ``schemaVersion`` and unknown
    ``status`` warnings through :func:`warnings.warn` and
    :func:`output.warn`, both landing on stderr. This variant captures
    those warnings and returns them on the result so callers decide
    whether to surface them.
    """
    import io
    import sys

    from . import output as _output

    root = coerce_path(root)
    captured_messages: list[str] = []

    redirect = io.StringIO()
    saved_stderr = sys.stderr
    sys.stderr = redirect
    try:
        with _warnings.catch_warnings(record=True) as caught:
            _warnings.simplefilter("always")
            data = read_workspace_file(root, feature, "tracker")
            validated = _validate_tracker_schema(data)
        captured_messages.extend(str(w.message) for w in caught)
    finally:
        sys.stderr = saved_stderr

    leaked = redirect.getvalue().strip().splitlines()
    for line in leaked:
        text = line.removeprefix("WARNING: ").strip()
        if text and text not in captured_messages:
            captured_messages.append(text)

    return TrackerReadResult(
        data=validated, advisories=tuple(captured_messages),
    )


def write_tracker(root: "Path | str", feature: str, data: TrackerData) -> None:
    """Write tracker using atomic_write_json."""
    root = coerce_path(root)
    write_workspace_file(root, feature, "tracker", data)


def require_tracker(root: "Path | str", feature: str, hint: str = "") -> TrackerData:
    """Read tracker or raise ``FileNotFoundError`` if missing."""
    root = coerce_path(root)
    data = require_workspace_file(
        root, feature, "tracker",
        hint=hint or "Run update-tracker.py to create one",
    )
    return _validate_tracker_schema(data)


def is_v2(tracker: dict) -> bool:
    """True when tracker uses the v2.0.0+ unified schema."""
    version = tracker.get("schemaVersion") or "1.0.0"
    try:
        parts = tuple(int(p) for p in str(version).split("."))
    except ValueError:
        return False
    return parts >= (2, 0, 0)


def finalize_and_save(root: Path, feature: str, tracker: TrackerData) -> None:
    """Recalculate summary, set updatedAt, and persist tracker."""
    tracker["summary"] = calculate_summary(tracker)
    tracker["updatedAt"] = sdd_time.ts_now()
    write_tracker(root, feature, tracker)


@dataclass(frozen=True)
class TrackerUpdateOutcome:
    """Outcome of a coordinator-side tracker mutation.

    ``updated`` is True when the tracker was both reachable and accepted
    the mutation. ``reason`` is empty on success and a short
    machine-routable string on failure (``"tracker-not-found"``,
    ``"invalid-doc-status"``). ``recovery_command`` is the literal shim
    line the agent runs to retry by hand — populated only on failure.
    """

    updated: bool
    reason: str
    recovery_command: str


def prepare_doc_status_update(
    tracker: TrackerData,
    repo_id: str,
    doc: str,
    status: str,
) -> "TrackerUpdateOutcome | None":
    """Validate the requested ``docStatus`` mutation in memory.

    Returns ``None`` on success (caller must persist), or a populated
    :class:`TrackerUpdateOutcome` describing the validation failure.
    Pure: no I/O, no recovery-command rendering — that lives in the
    public :func:`update_tracker_or_advisory` wrapper so callers can
    reuse the validation half without filesystem side-effects.
    """
    from .workspace_phase import update_doc_status

    try:
        update_doc_status(tracker, repo_id, doc, status)
    except ValueError as exc:
        return TrackerUpdateOutcome(
            updated=False,
            reason=f"invalid-doc-status: {exc}",
            recovery_command="",
        )
    return None


def persist_tracker_update(
    root: "Path | str",
    feature: str,
    tracker: TrackerData,
) -> None:
    """Write the in-memory tracker back to disk via :func:`finalize_and_save`."""
    finalize_and_save(coerce_path(root), feature, tracker)


def update_tracker_or_advisory(
    root: "Path | str",
    feature: str,
    repo_id: str,
    *,
    doc: str,
    status: str,
    workspace_path: str = ".",
) -> TrackerUpdateOutcome:
    """Set ``docStatus.{doc}`` → *status* in the workspace tracker.

    Returns :class:`TrackerUpdateOutcome` so callers can attach the
    failure reason to ``data.advisories[]`` instead of silently dropping
    the update. Composes :func:`prepare_doc_status_update` (pure
    validation) + :func:`persist_tracker_update` (I/O) so tests can
    exercise the validation half without filesystem side-effects.
    """
    from .command_templates import build_workspace_update_tracker_command

    root_path = coerce_path(root)

    def _recovery() -> str:
        return build_workspace_update_tracker_command(
            feature=feature,
            repo_id=repo_id,
            doc=doc,
            status=status,
            workspace_path=workspace_path,
        )

    tracker = read_tracker(root_path, feature)
    if not tracker:
        return TrackerUpdateOutcome(
            updated=False,
            reason="tracker-not-found",
            recovery_command=_recovery(),
        )

    failure = prepare_doc_status_update(tracker, repo_id, doc, status)
    if failure is not None:
        return TrackerUpdateOutcome(
            updated=failure.updated,
            reason=failure.reason,
            recovery_command=_recovery(),
        )

    persist_tracker_update(root_path, feature, tracker)
    return TrackerUpdateOutcome(
        updated=True, reason="", recovery_command="",
    )


def write_initial_tracker(
    workspace_root: "Path | str",
    feature: str,
    repos: list[dict],
) -> Path:
    """Materialise a v2.0.0 tracker with sane defaults.

    Mirrors :func:`workspace_manifest.write_initial_manifest`. Uses
    :func:`create_default_tracker` so docStatus / approvals defaults
    stay in one place.
    """
    from .paths import workspace_dir, WORKSPACE_TRACKER_FILENAME

    tracker = create_default_tracker(feature, repos=repos)
    write_tracker(workspace_root, feature, tracker)
    return workspace_dir(coerce_path(workspace_root), feature) / WORKSPACE_TRACKER_FILENAME


def tracker_repos_match(existing: TrackerData, supplied: list[dict]) -> bool:
    """True when the existing tracker's sub-spec projection matches *supplied*."""
    existing_subs = existing.get("subSpecs", []) or []
    return normalise_repo_set(existing_subs, key_field="repoId") == \
        normalise_repo_set(supplied, key_field="repoId")


def iter_workspace_subspecs(workspace_root: "str | Path"):
    """Yield ``(feature_name, tracker, sub_spec)`` for every sub-spec entry.

    Walks every feature dir under ``<workspace_root>/.spec-workflow/workspace``
    and reads its tracker through :func:`read_tracker_quiet`. Single
    traversal owner — both :func:`iter_workspace_repo_roots` (callers
    that only need the repo root path) and
    :mod:`sdd_core.workspace_query` (callers that need full sub-spec
    visibility) ride this iterator.
    """
    from . import paths as _paths

    workspace_str = str(workspace_root)
    base = (
        Path(workspace_str) / _paths.WORKFLOW_DIR / _paths.WORKSPACE_DIR_NAME
    )
    if not base.is_dir():
        return
    for feature_dir in base.iterdir():
        if not feature_dir.is_dir():
            continue
        try:
            tracker = read_tracker_quiet(workspace_str, feature_dir.name).data
        except (OSError, ValueError, KeyError):
            continue
        feature_name = tracker.get("feature") or feature_dir.name
        for entry in tracker.get("subSpecs") or []:
            if not isinstance(entry, dict):
                continue
            yield feature_name, tracker, entry


def iter_workspace_repo_roots(workspace_root: "str | Path"):
    """Yield each tracker-declared sub-spec repo root, deduped.

    Resolves ``repoPath`` for every sub-spec entry against
    *workspace_root* when not absolute, dedupes, and yields a
    :class:`Path`. Single owner shared between
    :mod:`sdd_core.reference_acks` and :mod:`sdd_core.workspace_query`
    so the resolution rules stay aligned.
    """
    import os as _os

    workspace_str = str(workspace_root)
    seen: set[str] = set()
    for _feature, _tracker, entry in iter_workspace_subspecs(workspace_root):
        repo_path = entry.get("repoPath")
        if not isinstance(repo_path, str) or not repo_path:
            continue
        resolved = (
            repo_path if _os.path.isabs(repo_path)
            else _os.path.normpath(_os.path.join(workspace_str, repo_path))
        )
        if resolved in seen:
            continue
        seen.add(resolved)
        yield Path(resolved)


def mark_review_retroactive(
    tracker: TrackerData, repo_id: str, phase: str, *, timestamp: str,
) -> None:
    """Stamp ``reviewMeta.{phase}`` with retroactive markers.

    The forensic record distinguishes "reviewed at the time" from
    "reviewed retroactively"; ``docStatus`` is left untouched (it was
    already at or beyond ``reviewed`` for the gap to be detectable).
    """
    sub_specs = tracker.get("subSpecs", [])
    sub = next((s for s in sub_specs if s.get("repoId") == repo_id), None)
    if sub is None:
        raise ValueError(f"Unknown repoId {repo_id!r} in tracker")
    review_meta = sub.setdefault("reviewMeta", {})  # type: ignore[index]
    phase_meta = review_meta.setdefault(phase, {})
    phase_meta["retroactive"] = True
    phase_meta["retroactiveAt"] = timestamp
